### ISSUE TITLE
GestionDPS Envoi mails

### ISSUE THREAD

**Issue by Loustik** [ProtectionCivile/intranet-protection-civile#13]
# Squelette
- [x] Mécanisme de construction du mail en fonction de l'état
- [x] Mécanisme de stockage du mail en base de données
- [x] Mécanisme d'envoi de mail à partir de la bdd (script)
- [ ] Paramétrage du CRON

# Différents types de mail à envoyer
- [x] Validation locale
- [x] Annulation DLO
- [x] Annulation DDO (demande mail supplémentaire à la pref
- [x] Mise en attente
- [x] Refus
- [x] Validation par DDO : Mail interne
- [x] Validation par DDO : Mail externe (préf. ou ADPC)

### Pour la Validation externe par le DDO :
- [x] Envoyer un email au DLO pour confirmation de poste (mail interne)
- [ ] Création d'une modale pour choix adresse mail (ajout & suppression) + texte (facultatif)
- [x] Choisir si préfecture 92 _ou_ Autre ADPC pour le destinataire

**Comment by bpasek** [comment]
# Subtasks

- [ ] Envoyer un e-mail pour le refus avec le motif à : DLO && cc DDO

- [ ] Envoyer un e-mail pour demande en attente de validation à DDO & cc DLO

### Sub-Subtasks Validation DDO : 

- [ ] Envoyer un email au DLO pour confirmation de poste

- [ ] Création d'une modale pour choix adresse mail (ajout & suppression) + texte (facultatif)

- [ ] Envoyer e-mail à SIDPC _ou_ Autre ADPC pour demande

**Comment by Loustik** [comment]
Utiliser un paramètre mail avec la liste des destinataires par défaut pour un refus / une acceptation. Utiliser des codes comme par exemple dlo-13 pour DLO section 13

Exemple :
- Pref-Accept-recipients = prefapdc, ddo, dlo
- Pref-reject-recipients = prefapdc, ddo, dlo
- dlo-validate-recipients = ddo, dlo
- dlo-validate-subject = Demande de DPS 

- A DLO on rajoute le numéro de commune. Si commune zéro alors département (ou alors dlo-0)
- Pref = @pref si notre département (à paramétrer). Sinon adpc-<num département>

- si hors département on rajoute la fnpc

Et ensuite remplacer ces paramètres avec par exemple :
- Ddo=@
- dlo-13 = mail de courbevoie@
- Pref=@
- Adpc75=@
- Fnpc=@

**Comment by Loustik** [comment]
Distinguer les récipients des ccrecipients

**Comment by Loustik** [comment]
commencé le mécanisme de construction du mail selon l'état. Les destinataires sont paramétrables, ceux en copie aussi. Le sujet et le corps du message ne le sont pas

**Comment by Loustik** [comment]
c'est fait mais non testé en réel. La seule chose qui manque c'est la possibilité d'ajouter ou de supprimer en live des destinataires. Si c'est un réel besoin, on fera une évol pour ça.
